/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // wikiSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro", // document ID
      label: "Quickstart",
      className: "quickStyle",
    },
    {
      type: "category",
      label: "Components",
      items: [
        "components/s3-lambda",
        "components/crud"
      ],
      className: "componentStyle",
    },
    {
      type: "category",
      label: "Modules",
      items: [
        
        "modules/base-module",
        "modules/email-auth-module",
        "modules/crud",
        "modules/customizable",
       
        
      ],
      className: "moduleStyle",
    },
    // {
    //   type: "category",
    //   label: "Code Walk Through",
    //   items: [
    //     "code-walk-through/introduction",
    //     "code-walk-through/rover-cli",
    //     "code-walk-through/rover-engine",
    //     "code-walk-through/code-walk-through",
    //   ],
    //   className: "contribution",
    // },
    {
      type: "category",
      label: "Contribution Gudelines",
      items: [
        
        "contribution/introduction",
        "contribution/rover-set-up",
        "contribution/define-new-components-or-module",
        "contribution/add-new-aws-service",
        "contribution/bug-report-or-feature-request",
        "contribution/bug-fix",
        "contribution/code-of-conduct",
       
        
      ],
      className: "contribution",
    },

  ]
};

module.exports = sidebars;
